### PR TITLE
These arbitrary

### PR DESCRIPTION
**Pull request by raronson**

### CODE REVIEW

**Comment by etorreborre** [comment]
:yum:

**Comment by domdere** [comment]
:flags:

**Comment by raronson** [comment]
As @charleso pointed out, its already in scalaz - https://github.com/scalaz/scalaz/blob/series/7.2.x/scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala#L25

**Comment by raronson** [comment]
Just for reference: Can't use the one from scalaz, compatibility issue, but there is one in mundane - https://github.com/ambiata/mundane/blob/master/mundane-testing/src/main/scala/com/ambiata/mundane/testing/Arbitraries.scala#L21

**Pull request closed without merging**
